namespace MgcPrxyDrftr.models { public partial class Contents { 
public long? BrrRetroArtifactUncommon { get; set; }
public long? BrrSchematicRareMythic { get; set; }
public long? ExtendedCommanderJumpstart { get; set; }
public long? FoilAltArt { get; set; }
public long? FoilBrrRetroArtifactSchematicUncommon { get; set; }
public long? FoilFullartBasic { get; set; }
public long? Transformers { get; set; }
public long? DoubleRainbowSerialized { get; set; }
public long? FoilTransformers { get; set; }
public long? BrrRetroArtifactRareMythic { get; set; }
public long? BrrSchematicUncommon { get; set; }
public long? FoilUncommonRetroArtifact { get; set; }
public long? RareMythicWithShowcase { get; set; }
public long? Infantry1 { get; set; }
public long? Infantry1Foils { get; set; }
public long? Infantry2 { get; set; }
public long? Infantry2Foils { get; set; }
public long? Powerstones1 { get; set; }
public long? Powerstones1Foils { get; set; }
public long? Powerstones2 { get; set; }
public long? Powerstones2Foils { get; set; }
public long? Titanic1 { get; set; }
public long? Titanic1Foils { get; set; }
public long? Titanic2 { get; set; }
public long? Titanic2Foils { get; set; }
public long? Unearthed1 { get; set; }
public long? Unearthed1Foils { get; set; }
public long? Unearthed2 { get; set; }
public long? Unearthed2Foils { get; set; }
public long? Welded1 { get; set; }
public long? Welded1Foils { get; set; }
public long? Welded2 { get; set; }
public long? Welded2Foils { get; set; }
 } 
public partial class Sheets { 
public Sheet BrrRetroArtifactUncommon { get; set; }
public Sheet BrrSchematicRareMythic { get; set; }
public Sheet ExtendedCommanderJumpstart { get; set; }
public Sheet FoilAltArt { get; set; }
public Sheet FoilBrrRetroArtifactSchematicUncommon { get; set; }
public Sheet FoilFullartBasic { get; set; }
public Sheet Transformers { get; set; }
public Sheet DoubleRainbowSerialized { get; set; }
public Sheet FoilTransformers { get; set; }
public Sheet BrrRetroArtifactRareMythic { get; set; }
public Sheet BrrSchematicUncommon { get; set; }
public Sheet FoilUncommonRetroArtifact { get; set; }
public Sheet RareMythicWithShowcase { get; set; }
public Sheet Infantry1 { get; set; }
public Sheet Infantry1Foils { get; set; }
public Sheet Infantry2 { get; set; }
public Sheet Infantry2Foils { get; set; }
public Sheet Powerstones1 { get; set; }
public Sheet Powerstones1Foils { get; set; }
public Sheet Powerstones2 { get; set; }
public Sheet Powerstones2Foils { get; set; }
public Sheet Titanic1 { get; set; }
public Sheet Titanic1Foils { get; set; }
public Sheet Titanic2 { get; set; }
public Sheet Titanic2Foils { get; set; }
public Sheet Unearthed1 { get; set; }
public Sheet Unearthed1Foils { get; set; }
public Sheet Unearthed2 { get; set; }
public Sheet Unearthed2Foils { get; set; }
public Sheet Welded1 { get; set; }
public Sheet Welded1Foils { get; set; }
public Sheet Welded2 { get; set; }
public Sheet Welded2Foils { get; set; }
 } }

