namespace MgcPrxyDrftr.models { public partial class Contents { 
public long? AboveTheClouds1 { get; set; }
public long? AboveTheClouds2 { get; set; }
public long? AboveTheClouds3 { get; set; }
public long? AboveTheClouds4 { get; set; }
public long? Angels1 { get; set; }
public long? Angels2 { get; set; }
public long? Archaeology1 { get; set; }
public long? Archaeology2 { get; set; }
public long? Archaeology3 { get; set; }
public long? Archaeology4 { get; set; }
public long? Basri { get; set; }
public long? Cats1 { get; set; }
public long? Cats2 { get; set; }
public long? Chandra { get; set; }
public long? Devilish1 { get; set; }
public long? Devilish2 { get; set; }
public long? Devilish3 { get; set; }
public long? Devilish4 { get; set; }
public long? Dinosaurs1 { get; set; }
public long? Dinosaurs2 { get; set; }
public long? Dinosaurs3 { get; set; }
public long? Dinosaurs4 { get; set; }
public long? Discarding1 { get; set; }
public long? Discarding2 { get; set; }
public long? Doctor1 { get; set; }
public long? Doctor2 { get; set; }
public long? Doctor3 { get; set; }
public long? Doctor4 { get; set; }
public long? Dogs1 { get; set; }
public long? Dogs2 { get; set; }
public long? Dragons1 { get; set; }
public long? Dragons2 { get; set; }
public long? Elves1 { get; set; }
public long? Elves2 { get; set; }
public long? Enchanted1 { get; set; }
public long? Enchanted2 { get; set; }
public long? FeatheredFriends1 { get; set; }
public long? FeatheredFriends2 { get; set; }
public long? FeatheredFriends3 { get; set; }
public long? FeatheredFriends4 { get; set; }
public long? Garruk { get; set; }
public long? Goblins1 { get; set; }
public long? Goblins2 { get; set; }
public long? Goblins3 { get; set; }
public long? Goblins4 { get; set; }
public long? HeavilyArmored1 { get; set; }
public long? HeavilyArmored2 { get; set; }
public long? HeavilyArmored3 { get; set; }
public long? HeavilyArmored4 { get; set; }
public long? Lands1 { get; set; }
public long? Lands2 { get; set; }
public long? Legion1 { get; set; }
public long? Legion2 { get; set; }
public long? Legion3 { get; set; }
public long? Legion4 { get; set; }
public long? Lightning1 { get; set; }
public long? Lightning2 { get; set; }
public long? Liliana { get; set; }
public long? Milling { get; set; }
public long? Minions1 { get; set; }
public long? Minions2 { get; set; }
public long? Minions3 { get; set; }
public long? Minions4 { get; set; }
public long? Minotaurs1 { get; set; }
public long? Minotaurs2 { get; set; }
public long? Phyrexian { get; set; }
public long? Pirates1 { get; set; }
public long? Pirates2 { get; set; }
public long? PlusOne1 { get; set; }
public long? PlusOne2 { get; set; }
public long? PlusOne3 { get; set; }
public long? PlusOne4 { get; set; }
public long? Predatory1 { get; set; }
public long? Predatory2 { get; set; }
public long? Predatory3 { get; set; }
public long? Predatory4 { get; set; }
public long? Rainbow { get; set; }
public long? Reanimated1 { get; set; }
public long? Reanimated2 { get; set; }
public long? Reanimated3 { get; set; }
public long? Reanimated4 { get; set; }
public long? Rogue2 { get; set; }
public long? Rogues1 { get; set; }
public long? Seismic { get; set; }
public long? Smashing1 { get; set; }
public long? Smashing2 { get; set; }
public long? Smashing3 { get; set; }
public long? Smashing4 { get; set; }
public long? Spellcasting1 { get; set; }
public long? Spellcasting2 { get; set; }
public long? Spellcasting3 { get; set; }
public long? Spellcasting4 { get; set; }
public long? Spirits1 { get; set; }
public long? Spirits2 { get; set; }
public long? Spooky1 { get; set; }
public long? Spooky2 { get; set; }
public long? Spooky3 { get; set; }
public long? Spooky4 { get; set; }
public long? Teferi { get; set; }
public long? TreeHugging1 { get; set; }
public long? TreeHugging2 { get; set; }
public long? TreeHugging3 { get; set; }
public long? TreeHugging4 { get; set; }
public long? UnderTheSea1 { get; set; }
public long? UnderTheSea2 { get; set; }
public long? Unicorns { get; set; }
public long? Vampires1 { get; set; }
public long? Vampires2 { get; set; }
public long? Vampires3 { get; set; }
public long? Vampires4 { get; set; }
public long? Walls { get; set; }
public long? WellRead1 { get; set; }
public long? WellRead2 { get; set; }
public long? WellRead3 { get; set; }
public long? WellRead4 { get; set; }
public long? Witchcraft1 { get; set; }
public long? Witchcraft2 { get; set; }
public long? Wizards1 { get; set; }
public long? Wizards2 { get; set; }
public long? Wizards3 { get; set; }
public long? Wizards4 { get; set; }
 } 
public partial class Sheets { 
public Sheet AboveTheClouds1 { get; set; }
public Sheet AboveTheClouds2 { get; set; }
public Sheet AboveTheClouds3 { get; set; }
public Sheet AboveTheClouds4 { get; set; }
public Sheet Angels1 { get; set; }
public Sheet Angels2 { get; set; }
public Sheet Archaeology1 { get; set; }
public Sheet Archaeology2 { get; set; }
public Sheet Archaeology3 { get; set; }
public Sheet Archaeology4 { get; set; }
public Sheet Basri { get; set; }
public Sheet Cats1 { get; set; }
public Sheet Cats2 { get; set; }
public Sheet Chandra { get; set; }
public Sheet Devilish1 { get; set; }
public Sheet Devilish2 { get; set; }
public Sheet Devilish3 { get; set; }
public Sheet Devilish4 { get; set; }
public Sheet Dinosaurs1 { get; set; }
public Sheet Dinosaurs2 { get; set; }
public Sheet Dinosaurs3 { get; set; }
public Sheet Dinosaurs4 { get; set; }
public Sheet Discarding1 { get; set; }
public Sheet Discarding2 { get; set; }
public Sheet Doctor1 { get; set; }
public Sheet Doctor2 { get; set; }
public Sheet Doctor3 { get; set; }
public Sheet Doctor4 { get; set; }
public Sheet Dogs1 { get; set; }
public Sheet Dogs2 { get; set; }
public Sheet Dragons1 { get; set; }
public Sheet Dragons2 { get; set; }
public Sheet Elves1 { get; set; }
public Sheet Elves2 { get; set; }
public Sheet Enchanted1 { get; set; }
public Sheet Enchanted2 { get; set; }
public Sheet FeatheredFriends1 { get; set; }
public Sheet FeatheredFriends2 { get; set; }
public Sheet FeatheredFriends3 { get; set; }
public Sheet FeatheredFriends4 { get; set; }
public Sheet Garruk { get; set; }
public Sheet Goblins1 { get; set; }
public Sheet Goblins2 { get; set; }
public Sheet Goblins3 { get; set; }
public Sheet Goblins4 { get; set; }
public Sheet HeavilyArmored1 { get; set; }
public Sheet HeavilyArmored2 { get; set; }
public Sheet HeavilyArmored3 { get; set; }
public Sheet HeavilyArmored4 { get; set; }
public Sheet Lands1 { get; set; }
public Sheet Lands2 { get; set; }
public Sheet Legion1 { get; set; }
public Sheet Legion2 { get; set; }
public Sheet Legion3 { get; set; }
public Sheet Legion4 { get; set; }
public Sheet Lightning1 { get; set; }
public Sheet Lightning2 { get; set; }
public Sheet Liliana { get; set; }
public Sheet Milling { get; set; }
public Sheet Minions1 { get; set; }
public Sheet Minions2 { get; set; }
public Sheet Minions3 { get; set; }
public Sheet Minions4 { get; set; }
public Sheet Minotaurs1 { get; set; }
public Sheet Minotaurs2 { get; set; }
public Sheet Phyrexian { get; set; }
public Sheet Pirates1 { get; set; }
public Sheet Pirates2 { get; set; }
public Sheet PlusOne1 { get; set; }
public Sheet PlusOne2 { get; set; }
public Sheet PlusOne3 { get; set; }
public Sheet PlusOne4 { get; set; }
public Sheet Predatory1 { get; set; }
public Sheet Predatory2 { get; set; }
public Sheet Predatory3 { get; set; }
public Sheet Predatory4 { get; set; }
public Sheet Rainbow { get; set; }
public Sheet Reanimated1 { get; set; }
public Sheet Reanimated2 { get; set; }
public Sheet Reanimated3 { get; set; }
public Sheet Reanimated4 { get; set; }
public Sheet Rogue2 { get; set; }
public Sheet Rogues1 { get; set; }
public Sheet Seismic { get; set; }
public Sheet Smashing1 { get; set; }
public Sheet Smashing2 { get; set; }
public Sheet Smashing3 { get; set; }
public Sheet Smashing4 { get; set; }
public Sheet Spellcasting1 { get; set; }
public Sheet Spellcasting2 { get; set; }
public Sheet Spellcasting3 { get; set; }
public Sheet Spellcasting4 { get; set; }
public Sheet Spirits1 { get; set; }
public Sheet Spirits2 { get; set; }
public Sheet Spooky1 { get; set; }
public Sheet Spooky2 { get; set; }
public Sheet Spooky3 { get; set; }
public Sheet Spooky4 { get; set; }
public Sheet Teferi { get; set; }
public Sheet TreeHugging1 { get; set; }
public Sheet TreeHugging2 { get; set; }
public Sheet TreeHugging3 { get; set; }
public Sheet TreeHugging4 { get; set; }
public Sheet UnderTheSea1 { get; set; }
public Sheet UnderTheSea2 { get; set; }
public Sheet Unicorns { get; set; }
public Sheet Vampires1 { get; set; }
public Sheet Vampires2 { get; set; }
public Sheet Vampires3 { get; set; }
public Sheet Vampires4 { get; set; }
public Sheet Walls { get; set; }
public Sheet WellRead1 { get; set; }
public Sheet WellRead2 { get; set; }
public Sheet WellRead3 { get; set; }
public Sheet WellRead4 { get; set; }
public Sheet Witchcraft1 { get; set; }
public Sheet Witchcraft2 { get; set; }
public Sheet Wizards1 { get; set; }
public Sheet Wizards2 { get; set; }
public Sheet Wizards3 { get; set; }
public Sheet Wizards4 { get; set; }
 } }

