namespace MgcPrxyDrftr.models { public partial class Contents { 
public long? Blink1 { get; set; }
public long? Blink2 { get; set; }
public long? Blink3 { get; set; }
public long? Blink4 { get; set; }
public long? Boneyard1 { get; set; }
public long? Boneyard2 { get; set; }
public long? Cats3 { get; set; }
public long? Cats4 { get; set; }
public long? Constellation1 { get; set; }
public long? Constellation2 { get; set; }
public long? Cruel1 { get; set; }
public long? Cruel2 { get; set; }
public long? Cruel3 { get; set; }
public long? Cruel4 { get; set; }
public long? Cycling1 { get; set; }
public long? Cycling2 { get; set; }
public long? Demons1 { get; set; }
public long? Demons2 { get; set; }
public long? Detective1 { get; set; }
public long? Detective2 { get; set; }
public long? Detective3 { get; set; }
public long? Detective4 { get; set; }
public long? Eldrazi { get; set; }
public long? Elves3 { get; set; }
public long? Elves4 { get; set; }
public long? Experimental1 { get; set; }
public long? Experimental2 { get; set; }
public long? Faeries1 { get; set; }
public long? Faeries2 { get; set; }
public long? Fangs1 { get; set; }
public long? Fangs2 { get; set; }
public long? Fangs3 { get; set; }
public long? Fangs4 { get; set; }
public long? Ferocious1 { get; set; }
public long? Ferocious2 { get; set; }
public long? Ferocious3 { get; set; }
public long? Ferocious4 { get; set; }
public long? Fiery1 { get; set; }
public long? Fiery2 { get; set; }
public long? Fiery3 { get; set; }
public long? Fiery4 { get; set; }
public long? Gigantic1 { get; set; }
public long? Gigantic2 { get; set; }
public long? GoToSchool1 { get; set; }
public long? GoToSchool2 { get; set; }
public long? Gross1 { get; set; }
public long? Gross2 { get; set; }
public long? Gross3 { get; set; }
public long? Gross4 { get; set; }
public long? Holy1 { get; set; }
public long? Holy2 { get; set; }
public long? Holy3 { get; set; }
public long? Holy4 { get; set; }
public long? Insects1 { get; set; }
public long? Insects2 { get; set; }
public long? Insects3 { get; set; }
public long? Insects4 { get; set; }
public long? Inventive1 { get; set; }
public long? Inventive2 { get; set; }
public long? Inventive3 { get; set; }
public long? Inventive4 { get; set; }
public long? Knights { get; set; }
public long? Landfall1 { get; set; }
public long? Landfall2 { get; set; }
public long? Law1 { get; set; }
public long? Law2 { get; set; }
public long? Law3 { get; set; }
public long? Law4 { get; set; }
public long? Merfolk1 { get; set; }
public long? Merfolk2 { get; set; }
public long? Merfolk3 { get; set; }
public long? Merfolk4 { get; set; }
public long? Morbid1 { get; set; }
public long? Morbid2 { get; set; }
public long? MultiHeaded1 { get; set; }
public long? MultiHeaded2 { get; set; }
public long? Primates { get; set; }
public long? Raid1 { get; set; }
public long? Raid2 { get; set; }
public long? Raid3 { get; set; }
public long? Raid4 { get; set; }
public long? Rats { get; set; }
public long? Scrying1 { get; set; }
public long? Scrying2 { get; set; }
public long? Shapeshifters { get; set; }
public long? Snow { get; set; }
public long? Speedy { get; set; }
public long? Spicy { get; set; }
public long? Teamwork1 { get; set; }
public long? Teamwork2 { get; set; }
public long? ThinkAgain1 { get; set; }
public long? ThinkAgain2 { get; set; }
public long? ThinkAgain3 { get; set; }
public long? ThinkAgain4 { get; set; }
public long? Treasure1 { get; set; }
public long? Treasure2 { get; set; }
public long? Treasure3 { get; set; }
public long? Treasure4 { get; set; }
public long? UnluckyThirteen { get; set; }
public long? Urzas { get; set; }
public long? Vehicles { get; set; }
public long? Wolves1 { get; set; }
public long? Wolves2 { get; set; }
public long? Wolves3 { get; set; }
public long? Wolves4 { get; set; }
public long? Zombies1 { get; set; }
public long? Zombies2 { get; set; }
public long? Zombies3 { get; set; }
public long? Zombies4 { get; set; }
 } 
public partial class Sheets { 
public Sheet Blink1 { get; set; }
public Sheet Blink2 { get; set; }
public Sheet Blink3 { get; set; }
public Sheet Blink4 { get; set; }
public Sheet Boneyard1 { get; set; }
public Sheet Boneyard2 { get; set; }
public Sheet Cats3 { get; set; }
public Sheet Cats4 { get; set; }
public Sheet Constellation1 { get; set; }
public Sheet Constellation2 { get; set; }
public Sheet Cruel1 { get; set; }
public Sheet Cruel2 { get; set; }
public Sheet Cruel3 { get; set; }
public Sheet Cruel4 { get; set; }
public Sheet Cycling1 { get; set; }
public Sheet Cycling2 { get; set; }
public Sheet Demons1 { get; set; }
public Sheet Demons2 { get; set; }
public Sheet Detective1 { get; set; }
public Sheet Detective2 { get; set; }
public Sheet Detective3 { get; set; }
public Sheet Detective4 { get; set; }
public Sheet Eldrazi { get; set; }
public Sheet Elves3 { get; set; }
public Sheet Elves4 { get; set; }
public Sheet Experimental1 { get; set; }
public Sheet Experimental2 { get; set; }
public Sheet Faeries1 { get; set; }
public Sheet Faeries2 { get; set; }
public Sheet Fangs1 { get; set; }
public Sheet Fangs2 { get; set; }
public Sheet Fangs3 { get; set; }
public Sheet Fangs4 { get; set; }
public Sheet Ferocious1 { get; set; }
public Sheet Ferocious2 { get; set; }
public Sheet Ferocious3 { get; set; }
public Sheet Ferocious4 { get; set; }
public Sheet Fiery1 { get; set; }
public Sheet Fiery2 { get; set; }
public Sheet Fiery3 { get; set; }
public Sheet Fiery4 { get; set; }
public Sheet Gigantic1 { get; set; }
public Sheet Gigantic2 { get; set; }
public Sheet GoToSchool1 { get; set; }
public Sheet GoToSchool2 { get; set; }
public Sheet Gross1 { get; set; }
public Sheet Gross2 { get; set; }
public Sheet Gross3 { get; set; }
public Sheet Gross4 { get; set; }
public Sheet Holy1 { get; set; }
public Sheet Holy2 { get; set; }
public Sheet Holy3 { get; set; }
public Sheet Holy4 { get; set; }
public Sheet Insects1 { get; set; }
public Sheet Insects2 { get; set; }
public Sheet Insects3 { get; set; }
public Sheet Insects4 { get; set; }
public Sheet Inventive1 { get; set; }
public Sheet Inventive2 { get; set; }
public Sheet Inventive3 { get; set; }
public Sheet Inventive4 { get; set; }
public Sheet Knights { get; set; }
public Sheet Landfall1 { get; set; }
public Sheet Landfall2 { get; set; }
public Sheet Law1 { get; set; }
public Sheet Law2 { get; set; }
public Sheet Law3 { get; set; }
public Sheet Law4 { get; set; }
public Sheet Merfolk1 { get; set; }
public Sheet Merfolk2 { get; set; }
public Sheet Merfolk3 { get; set; }
public Sheet Merfolk4 { get; set; }
public Sheet Morbid1 { get; set; }
public Sheet Morbid2 { get; set; }
public Sheet MultiHeaded1 { get; set; }
public Sheet MultiHeaded2 { get; set; }
public Sheet Primates { get; set; }
public Sheet Raid1 { get; set; }
public Sheet Raid2 { get; set; }
public Sheet Raid3 { get; set; }
public Sheet Raid4 { get; set; }
public Sheet Rats { get; set; }
public Sheet Scrying1 { get; set; }
public Sheet Scrying2 { get; set; }
public Sheet Shapeshifters { get; set; }
public Sheet Snow { get; set; }
public Sheet Speedy { get; set; }
public Sheet Spicy { get; set; }
public Sheet Teamwork1 { get; set; }
public Sheet Teamwork2 { get; set; }
public Sheet ThinkAgain1 { get; set; }
public Sheet ThinkAgain2 { get; set; }
public Sheet ThinkAgain3 { get; set; }
public Sheet ThinkAgain4 { get; set; }
public Sheet Treasure1 { get; set; }
public Sheet Treasure2 { get; set; }
public Sheet Treasure3 { get; set; }
public Sheet Treasure4 { get; set; }
public Sheet UnluckyThirteen { get; set; }
public Sheet Urzas { get; set; }
public Sheet Vehicles { get; set; }
public Sheet Wolves1 { get; set; }
public Sheet Wolves2 { get; set; }
public Sheet Wolves3 { get; set; }
public Sheet Wolves4 { get; set; }
public Sheet Zombies1 { get; set; }
public Sheet Zombies2 { get; set; }
public Sheet Zombies3 { get; set; }
public Sheet Zombies4 { get; set; }
 } }

