<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AppConfig>App.$(Configuration).config</AppConfig>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <Authors>RetroLotti</Authors>
    <Product>Magic the Gathering Proxy Drafter</Product>
    <SignAssembly>false</SignAssembly>
    <AssemblyOriginatorKeyFile>ProxyDrator.snk</AssemblyOriginatorKeyFile>
    <DelaySign>false</DelaySign>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.ico</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="json\decks\**" />
    <EmbeddedResource Remove="json\decks\**" />
    <None Remove="json\decks\**" />
    <Compile Remove="**\obj\**\*.cs;**\bin\**\*.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="FreeSpire.PDF" Version="12.4.0" />
    <PackageReference Include="HeyRed.ImageSharp.Heif" Version="2.1.3" />
    <PackageReference Include="LibHeif.Native" Version="1.15.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.7" />
    <PackageReference Include="MtgApiManager.Lib" Version="2.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="QuestPDF" Version="2026.2.4" />
    <PackageReference Include="ScryfallAPI.Client" Version="3.1.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.7" />
    <PackageReference Include="TextCopy" Version="6.2.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="icon.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="scripts\booster.noguid.v1.nde">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="scripts\booster.noguid.v2.nde">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="scripts\booster.noguid.v3.nde">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="scripts\booster.v1.nde">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="scripts\booster.v2.nde">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="scripts\booster.v3.nde">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="cache\" />
    <Folder Include="models\upgrades\" />
    <Folder Include="temporary\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Users\19137590\source\repos\RetroLotti\open-boosters-api\src\client\OpenBoosters.Api\OpenBoosters.Api.csproj" />
  </ItemGroup>

</Project>
